version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: conference-website
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl-certs:/etc/letsencrypt:ro  # Mount the entire ssl-certs directory

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl-certs:/etc/letsencrypt  # Same mount
      - .:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email bhusan@ncit.edu.np --agree-tos --no-eff-email -d conference.ncit.edu.np --non-interactive